### ISSUE TITLE
Can't Install Add-on with FireFox 50.0.2/Windows 10 Enterprise

### ISSUE THREAD

**Issue by jkirwan** [bs-detector/bs-detector#114]
### Extension version
0.2.7

### Browser and browser version
Firefox 50.0.2

### OS and OS version
Windows 10 Enterprise

### Expected behavior
Install add-on

### Actual behavior
Refuses to install add-on, indicating that it is "corrupt." This happens when I visit the mozilla add-on linked to by your page... this one, in particular:

  https://addons.mozilla.org/en-US/firefox/addon/bsdetector/

If I then click on the "info" link on the far right side of the page, adjacent to this text "Version 0.2.7", it takes me to the bottom of the page with additional info showing. Including another link I can click to install the add-on. When I click _that_ link, the following popup message occurs:

"Caution: This add-on has not been reviewed by Mozilla and can't be installed on release versions of Firefox 43 and above. Be careful when installing third-party software that might harm your computer."

And again, I also get the "corrupt" message from Firefox when I override the message and request an installation.

### Steps to reproduce  behavior
See above under "actual behavior."

I have turned off all add-ons prior to attempting this installation, as well. I have not, though, uninstalled Firefox and re-installed it.

**Comment by Bastlynn** [comment]
From a quick google on the error message it looks like it may be related to the unsigned status (the extension is currently undergoing review by mozilla): https://support.mozilla.org/en-US/questions/1095256 - I'll keep looking for other causes but at the moment I think it's likely signing is the issue here.

**Comment by Bastlynn** [comment]
https://community.qualys.com/docs/DOC-5607 seems to confirm that an unsigned plugin registers as "corrupt".

**Comment by jkirwan** [comment]
Thanks. I agree that's the problem. It will then have to wait until Mozilla gets a chance to sign it, I suppose. Hopefully, that process doesn't cause me to age a few more years. :) Thanks.

**Comment by selfagency** [comment]
maybe we should put back instructions on how to self-install for now cuz... 😴
<img width="548" alt="screenshot 2016-12-07 13 55 27" src="https://cloud.githubusercontent.com/assets/2541728/20981969/a4466946-bc84-11e6-8398-a04e5ead16a8.png">

**Comment by tomlutzenberger** [comment]
Is this still an issue?

**Comment by jkirwan** [comment]
It is for me. Just tested it again. Same results.

**Comment by Bastlynn** [comment]
Mozilla can end up taking a lot of time on their review since it's a manual process. At last check we're around 250 in the queue. :-/

**Comment by tomlutzenberger** [comment]
So it will be solved sooner or later. From my POV, this can be closed.
