### ISSUE TITLE
Attention: npm update makes gulp unexecutable

### ISSUE THREAD

**Issue by tomlutzenberger** [bs-detector/bs-detector#118]
Running an update on npm may get you in trouble.
It causes an error in [gulp-clean-css](https://www.npmjs.com/package/gulp-clean-css), which is already filed as issue: https://github.com/scniro/gulp-clean-css/issues/19
The module is missing `gulp-concat` for some reason.

To prevent making gulp unusable but run with the latest changes, you can *temporarily* add follwing to `devDependencies` in your package.json:
```javascript
    "gulp-concat": "^2.6.1",
```

**Comment by scniro** [comment]
fixed on my end in 0b6914e461ac306c7c3cf437e403c5b0bf12586c

**Comment by scniro** [comment]
[2.1.3 published](https://www.npmjs.com/package/gulp-clean-css) - sorry!

**Comment by tomlutzenberger** [comment]
Thx!
